repos:
  - repo: https://github.com/JohnnyMorganz/stylua
    rev: v2.5.2
    hooks:
      - id: stylua
        types: [lua]

  - repo: local
    hooks:
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        pass_filenames: false
